apt-get install python3-psycopg2

python3 manage.py migrate

pip install Werkzeug

docker run -p 8000:8000 -it integration1
python3 manage.py createsuperuser


macos-things:
    (echo; echo 'eval "$(/opt/homebrew/bin/brew shellenv)"') >> /Users/andorgunczer/.zprofile
    eval "$(/opt/homebrew/bin/brew shellenv)"
    update pip -> /Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip
    brew services start postgresql@16
    openssl req -newkey rsa:2048 -nodes -keyout key.pem -x509 -days 365 -out cert.crt
    psql -d postgres -U andorgunczer (-d datenbank -U zu wem das Datenbank gehoert) (\d: um tabels von dem Datenbank zu schauen)
    
    Pre insert Avatar paths
        Syntax:
    INSERT INTO table(column1, column2, …)
    VALUES
        (value1, value2, …);

    Insert without console -> psql -d transcendence -U andorgunczer -c "INSERT INTO transcendence_avatar (path, name) VALUES ('/Users/andorgunczer/WORK/SCHOOL/transcendence/development/transcendence/files/dog_avatar.jpg', 'dog');"

    export PATH=/opt/homebrew/Cellar/postgresql@16/16.3/bin:$PATH
    DELETE FROM transcendence_users2;

    PROBLEM:

        python3 manage.py creatasuperuser returns error message for missing ID;

    SOLUTION:

        DROP DATABASE transcendence;
        CREATE DATABASE transcendence OWNER project;

TERMINOLOGY:
    Primary Key vs Candidate Key:
        - Primary key uniquely identifies a record, but its value cannot be NULL
        - Candidate Key also has the abiklity to uniquely identify a record, however, should contain minimum fields/ aka null value is possible.
    Non-Prime attribute: Cannot identify a record uniquely (derived)

to run server in secure mode: python3 manage.py runserver_plus --cert-file /Users/andorgunczer/WORK/SCHOOL/transcendence/files/cert.crt --key-file /Users/andorgunczer/WORK/SCHOOL/transcendence/files/key.pem

DOCKER SETUP:

    docker build . -t main_app

    docker run -p 8000:8000 -it main_app --name main_app

    to get contractAddress: node scripts/deploy.js | grep "0x" | cut -c 31-

    docker exec -it main_app /bin/bash


Common Docker Error: transcendence.models.Users2.DoesNotExist: Users2 matching query does not exist.
    Solution 1: Delete migrations

    Error: session cookies are from the previous build of docker. When a new instance is built, the app will extract the user from the session token, however, the user that was registered in the last docker instance, does not exist in the new one.
    Probable Solutions: Try the function, upon failure load default website with an alert error message.

    
Django error: Static images directory does not exist
    